x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: 1.1.4
  publishedVersionMetadata:
    releaseNote: >-
      A regular update.
    releaseTypes:
      - Feature
    recommended: false

  clusterConstraints:
    resources:
      - replicas: 1
        requests:
          cpu: 100m
          memory: 100Mi

  images:
    "":
      properties:
        deepgramSelfHostedStarter.image.repo:
          type: REPO_WITH_REGISTRY
          default: gcr.io/deepgram-public/deepgram-self-hosted-starter
        deepgramSelfHostedStarter.image.tag:
          type: TAG
          default: 1.1.4
    ubbagent:
      properties:
        ubbagentFull:
          type: FULL
          default: gcr.io/cloud-marketplace-tools/metering/ubbagent:latest

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  usageReportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET

required:
  - name
  - namespace
