---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "deepgram-public", "product_id": "deepgram-self-hosted-starter", "partner_name": "Deepgram"}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: DeepgramSelfHostedStarter
    version: "{{ .Values.deepgramSelfHostedStarter.image.tag }}"
    description: >-
       A Helm chart for running a starter Deepgram application in a self-hosted environment.
    maintainers:
    - name: Deepgram Self-Hosted
      email: self.hosted@deepgram.com
    links:
    - description: Deepgram Developer Documentation
      url: https://developers.deepgram.com
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: apps
    kind: Deployment
  - group: core
    kind: Service
