apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-starter-app
  labels: &DeploymentLabels
    name: "{{ .Release.Name }}"
    app: deepgram-self-hosted-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepgram-self-hosted-starter
  template:
    metadata:
      labels: *DeploymentLabels
    spec:
      containers:
      - name: {{ .Release.Name }}-starter-app
        image: "{{ .Values.deepgramSelfHostedStarter.image.repo }}:{{ .Values.deepgramSelfHostedStarter.image.tag }}"
        ports:
          - name: http
            containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
        readinessProbe:
          tcpSocket:
            port: 80
      - name: ubbagent
        image: $imageUbbagent
        env:
        - name: AGENT_CONFIG_FILE
          value: "/etc/ubbagent/config.yaml"
        - name: AGENT_LOCAL_PORT
          value: "4567"
        - name: AGENT_ENCODED_KEY
          valueFrom:
            secretKeyRef:
              name: $usageReportingSecret
              key: reporting-key
        - name: AGENT_CONSUMER_ID
          valueFrom:
            secretKeyRef:
              name: $usageReportingSecret
              key: consumer-id
        volumeMounts:
        - name: ubbagent-config
          mountPath: /etc/ubbagent
      volumes:
      - name: ubbagent-config
        configMap:
          name: {{ .Release.Name}}-ubbagent-config
