apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-starter-app
  labels: &DeploymentLabels
    name: "{{ .Release.Name }}"
    app: deepgram-self-hosted-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepgram-self-hosted-starter
  template:
    metadata:
      labels: *DeploymentLabels
    spec:
      containers:
      - name: {{ .Release.Name }}-starter-app
        image: "{{ .Values.deepgramSelfHostedStarter.image.repo }}:{{ .Values.deepgramSelfHostedStarter.image.tag }}"
        ports:
          - name: http
            containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
        readinessProbe:
          tcpSocket:
            port: 80
