apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-starter-svc
  labels: &ServiceLabels
    name: "{{ .Release.Name }}"
spec:
  selector:
    app: deepgram-self-hosted-starter
  ports:
    - name: "primary"
      port: 80
      targetPort: 80

