apiVersion: v2
name: deepgram-self-hosted-starter
type: application
version: 1.1.1
appVersion: 1.1.1
description: A Helm chart for running a starter Deepgram application in a self-hosted environment
sources: ["https://github.com/deepgram/gcp-marketplace-listing"]
kubeVersion: ">=1.27.0-0"
maintainers:
  - name: Deepgram Self-Hosted
    email: self.hosted@deepgram.com
icon: "https://www.dropbox.com/scl/fi/v4jtfbsrx881pbevcga3j/D-icon-black-square-250x250.png?rlkey=barv5jeuhd7t2lczz0m3nane7&dl=1"
